# Generated by Django 4.2.23 on 2025-08-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardpreferences",
            name="test",
            field=models.BooleanField(default=False),
        ),
    ]
