# Generated by Django 4.2 on 2025-08-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_dashboardpreferences_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashboardpreferences",
            name="test",
        ),
        migrations.AlterField(
            model_name="dashboardpreferences",
            name="data",
            field=models.TextField(default="{}"),
        ),
    ]
